listenAddr = ":8083" 
logFilePath = "" 
mode = "release" # debug or release
swapMaxLimit = "150000000" #decimals 6
swapMinLimit = "1000000" #decimals 6
swapRate = "1600000" #decimals 6

[[tokenInfo]]
AccountPrefix = "cosmos"
CoinGeckoSymbol = "cosmos"
CoinMarketSymbol = "ATOM"
Endpoint = "http://127.0.0.1:16657"
PoolAddress = "cosmos13mwxtgrljf9d5r72sc28496ua4lsga0jvmqz8x"
StartHeight = 0

[db]
host = "127.0.0.1" # mysql host ip
name = "station" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username
