logFilePath = "" 
taskTicker = 15 # seconds

coinGeckoApi = "https://api.coingecko.com/api/v3/simple/price"
coinMarketApi = "https://web-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest"

[db]
host = "127.0.0.1" # mysql host ip
name = "station" # the database this server used
port = "3306" 
pwd = "123456" # mysql password
user = "root" # mysql username
